### ISSUE TITLE
winapi error #42

### ISSUE THREAD

**Issue by ababo** [sstallion/go-hid#6]
I get the following panic on Windows:
```
2023/06/22 18:05:46 panic was raised: winapi error #42, stack: goroutine 13 [running]:
runtime/debug.Stack()
	C:/Program Files/Go/src/runtime/debug/stack.go:24 +0x65
github.com/inspera/inspera-launcher/util.Recover(0xc004ef1f18)
	C:/msys64/home/ababo/launcher/util/misc.go:25 +0x45
panic({0x7ff756f11260, 0x7ff756b473f0})
	C:/Program Files/Go/src/runtime/panic.go:884 +0x213
github.com/sstallion/go-hid.wcstogo(0x299ba598490)
	C:/Users/ababo/go/pkg/mod/github.com/sstallion/go-hid@v0.14.0/wchar.go:73 +0x1a5
github.com/sstallion/go-hid.newDeviceInfo(0x299ba5a0480)
	C:/Users/ababo/go/pkg/mod/github.com/sstallion/go-hid@v0.14.0/hid.go:123 +0x45
github.com/sstallion/go-hid.Enumerate(0x0?, 0x0?, 0xc004ef1ce0)
	C:/Users/ababo/go/pkg/mod/github.com/sstallion/go-hid@v0.14.0/hid.go:148 +0x94
github.com/inspera/inspera-launcher/sentinel.hidDevices()
	C:/msys64/home/ababo/launcher/sentinel/hid.go:64 +0x51
github.com/inspera/inspera-launcher/sentinel.newHIDMonitor(0xc00029ea80, 0xc002b3c870?)
	C:/msys64/home/ababo/launcher/sentinel/hid.go:25 +0x71
github.com/inspera/inspera-launcher/sentinel.Start(0xc000672000, 0xc00029ea80, 0xc002b3c870)
	C:/msys64/home/ababo/launcher/sentinel/sentinel.go:37 +0xfc
main.start(0xc0000c6210)
	C:/msys64/home/ababo/launcher/main.go:231 +0x7aa
main.main.func1()
	C:/msys64/home/ababo/launcher/main.go:356 +0x45
created by main.main
	C:/msys64/home/ababo/launcher/main.go:354 +0xa45
```

**Comment by sstallion** [comment]
Thanks for reporting this @ababo. It looks like @koron has a PR up to address this (#7). Changes look pretty good, I think it's just a matter of making a few adjustments for alignment. Once everything is merged I'll make sure to cut a new release for you guys.
